---
title: "ITTF Rankings Rvest"
author: "KF"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: show
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
	echo=TRUE,
	message=FALSE,
	warning=FALSE,
	eval=TRUE
)

gc()
```

## Background

In this script, I will be scraping ITTF rankings data from the [ITTF rankings](https://www.ittf.com/rankings/) website using the `rvest` R package.

## Import

### Packages + Functions

```{r}
#Core packages/functions
library(tidyverse)
library(rvest)
library(plotly)

#Additional packages
library(bslib)
```

## Webscrape

```{r}
url <- "https://www.ittf.com/wp-content/uploads/2022/05/2022_19_SEN_MS.html"

#save scraped ver of page
saved_html <- read_html(url)
```

```{r}
#custom function to obtain html text based on passed in searchTerm
extractText <- function(searchTerm){
  temp <- saved_html %>% html_nodes(searchTerm) %>% html_text()
  return(temp)
}

#obtain dataset title
dfTitle <- extractText("td.listdataleft")

#obtain dataset row title
# dfRowname <- extractText("tr.tablehead") %>% str_split_fixed(" ",4)

#extract rankings data
bulkData <- extractText("tr.rrow") %>% as.data.frame()
```

## Tidying Scraped Data

```{r}
#custom function to simplify regex
regexText <- function(searchTerm,colName="."){
  temp <- bulkData[[colName]] %>% str_extract(searchTerm)
  return(temp)
}

#extract rank change
bulkData$rankChange <- regexText("\\s(↑|↓){1}\\d{1,3}") %>% str_replace_all(" ","")

#replace rank change w/ blank
bulkData$. <- bulkData$. %>% str_replace("\\s(↑|↓){1}\\d{1,3}","")

#extract rank
bulkData$rank <- regexText("\\d{1,3}")

#extract points
bulkData$points <- regexText("\\d+\\s$") %>% str_replace_all(" ","") %>% as.numeric()

#extract name
bulkData$name <- regexText("[^0-9]+")

#extract association
bulkData$assoc <- regexText("[A-Z]{3}\\s$","name")

#rm assoc from name
for(i in 1:nrow(bulkData)){
  bulkData$name[i] <- str_remove_all(bulkData$name[i],bulkData$assoc[i])
}

#rm spaces + tidy even more
bulkData <- bulkData %>% separate(name,as.character(1:6),sep=" ")
bulkData$`5` <- ifelse(bulkData$`5`=="",NA,bulkData$`5`)
bulkData$playerName <- paste(bulkData$`3`,bulkData$`4`,bulkData$`5`) %>% str_replace_all("NA","")

#final ver
bulkData <- bulkData %>% select(contains(c("rank","player","assoc","points"))) %>% relocate("rankChange",.after="rank")

names(bulkData) <- c("Rank Only","Rank Change","Name","Assoc","Points")

bulkData$`Rank Only` <- as.numeric(bulkData$`Rank Only`)
```

## Plot

```{r}
#param
n_players <- 30

ittf_data <- bulkData %>% filter(`Rank Only`<=n_players)
```

```{r}
ittf_data
```

```{r}
#made w/ ggplot
ittf_data %>%
  ggplot(aes(Points,reorder(Name,Points),fill=Assoc))+
  geom_bar(stat="identity")+
  labs(x="Total Number of Points",y="Player Name",
       title=cat("Points and Association for Top",n_players,
                 "Ranked Players",sep=" "))
```

```{r}
#made w/ plotly
ittf_data %>% 
  plot_ly(x=~Points,y=~reorder(Name,Points),color=~Assoc) %>%
  add_bars() %>%
  layout(xaxis=list(title="Total Number of Points"),
         yaxis=list(title="Player Name"),
         title=list(title=cat("Points and Association for Top",
                              n_players,"Ranked Players",sep=" ")))
```
